### ISSUE TITLE
Backpack image is not big when holding blocks from another screen

### ISSUE THREAD

**Issue by ajcolter** [mit-cml/appinventor-sources#630] opened 2015-12-08 17:17 UTC
On Screen2 of my app, I added blocks to the backpack.
Going to Screen1 from the blocks editor, the backpack is the smaller image, although it contains the blocks from Screen2. 
It should be the larger backpack image because blocks are in it, even though I didn't add them on Screen1.

**Comment by josmas** [comment] 2016-02-14 21:35
Has anyone worked on this? Funnily enough, I cannot reproduce the description above, BUT if you delete all blocks from the backpack in say Screen2 and change to Screen1, the backpack shows as full even though it has no blocks in it. Can someone else confirm?

**Comment by josmas** [comment] 2016-02-14 21:54
Actually, this is kinda random; now I can reproduce the behaviour in the first message. There's definitely something odd going on!

**Comment by josmas** [comment] 2016-02-14 23:00
A bit more info here; it seems like a different backpack object is created with each Screen, so even though the contents are shared between all objects, the state is not, and each of the screens is not aware of what happened in the previous one.

Two things that can be done:
1. Figure out how the state is shared, and do the same for state.
2. Re-design this in a similar way to TypeBlocking, in which only one object is created, and is shared among all screens.

There also seems to be some kind of confusion between the states _isOpen_ and _isLarge_ (seem to be the same thing at times, but not always).

**Comment by josmas** [comment] 2016-02-15 00:05
For point 1 above, there are two functions to set and get backpack that are _pushed up_ to GWT (see functions in BloclyPanel.java. That's how the blocks are shared between Blockly instances, because those functions are defined as `window.parent.BlocklyPanel_getBackpack();`. The state of the icon (open/close or large/small or empty/full) could be shared in the same way.

**Comment by ajcolter** [comment] 2016-02-15 01:14
So I think we've decided to abandon making the backpack bigger when it has blocks in it. However, it will be a new backpack image that shows blocks in it if it has blocks. So if it doesn't know about the state between screens, that could be a problem.

I think the isOpen state is a hover-state?

**Comment by josmas** [comment] 2016-02-15 11:02
@ajcolter the new images are already in (in master; not deployed). The third state is indeed a hover state.

**Comment by wadleo** [comment] 2016-04-20 08:00
Hi @josmas @jisqyv 
I have been researching on this based on the recommendations @josmas stated above and noticed that the backpack [] array is static and that's the way the contents are shared between variables. Therefore, the problem comes when we the when screens are switched and the YaBlocksEditor.onBlocksAreaChanged(String formName) method does not check to see if there are some backpack contents. Hope my understanding is correct.
@jisqyv should i continue on this cause i see this issue is assigned to you, thanks and eagerly waiting for your replies.

**Closed** 2018-12-12 15:56 UTC
Labels: bitesize, help wanted, hints provided
