### ISSUE TITLE
Correct value of selection index with filtered list pickers

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#406] opened 2015-06-03 01:21 UTC
Below sample shows how filtering works. Select 1st a and then last a. On each selection, the selected text, index will display.

Next, toggle filter and click on same selections. Notice the selectionIndex. Taifun's recommendation is to keep / show the original unfiltered index. I can see the benefit in it, but not sure on how to accomplish it.

Try test app here: http://3nportal.com/temp/TestListView.aia

**Comment by Momoumar** [comment] 2015-08-20 17:09
@halatmit,
I was not able to reproduce this bug on a One Plus One running Android 5.0.2.

**Comment by halatmit** [comment] 2015-08-20 17:16
Are you saying that the selection index now refers to the position in the
unfiltered list?
If so, we can close the issue.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by Momoumar** [comment] 2015-08-20 17:21
Yes that is correct. The index are fine whether or not filter is toggled.

**Comment by Momoumar** [comment] 2015-08-20 17:24
Oh I think I've missedsomething. 
The bug is that the filtered text should show the index of the unfiltered one ?

**Comment by halatmit** [comment] 2015-08-20 17:33
The correct behavior is that the selection index should be the index in the
unfiltered list, not the index in the filtered list.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by Momoumar** [comment] 2015-08-20 17:41
Noted.

**Comment by jisqyv** [comment] 2016-07-17 20:43
Fixed in #695 now merged into UCR

**Closed by jisqyv** 2016-07-17 20:43 UTC
