### ISSUE TITLE
Missing icons in blocks editor component list

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#372] opened 2015-04-29 01:09 UTC
From Taifun:

create an empty project and drag a TinyDB component into the working space, now go to the blocks editor and you will see this (the TinyDB icon is missing)
now go back to the designer, add a slider control, go back to the blocks editor and you will see this: (TinyDB icon appears in component list on the left, Slider icon is missing)

add a button and the slider still is missing, delete the button and the slider icon appears

strange, isn't it? I'm  on Windows 7 using Google Chrome

From Hal:
I tried this on a Mac and I see the bad behavior in Chrome, but not in Firefox.  If I had to guess, I'd say it's an HTML error on the project page, or (shudder) a result of updating GWT.

**Comment by Momoumar** [comment] 2015-05-18 18:15
I experienced this also, It occurs in Safari and Chrome but not in Firefox. The thing is that, it doesn't display the first icon of a nonVisibleComponent. 
For example:
If you create an empty project and drag two TinyDB component it will only show the icon of the second TinyDB component on the Block Editor. 
If you create an empty project and drag a button and a TinyDB component it will only show the icon of the button on the Block Editor.
And so on ...

**Comment by halatmit** [comment] 2015-05-29 19:51
@Momoumar @jsheldonmit 
This "happens in chrome but not in Firefox" behavior tends to be some kind of HTML bug.   Firefox is somethimes more forgiving than Chrome about things like balancing quote or tags.

**Comment by halatmit** [comment] 2015-05-29 21:34
See the forum thread here
https://groups.google.com/forum/#!msg/app-inventor-dev/kPZGchQgfCQ/aKZR9dfA4aQJ

**Comment by Momoumar** [comment] 2015-05-30 21:59
Thanks @halatmit, I will look on it.

**Comment by fmntf** [comment] 2015-07-06 10:42
I have no access to app-inventor-dev forum, by the way I investigated a little bit.
The icon is missing since the `<img>` tag has `style="width:0px;...`. The width is computed in `$buildTree` via `$getWidth(this$static.iconImage)`. Calling `$getWidth` twice leads to a the width  computed correctly.

`$getWidth` just returns `iconImage.element.width`. Probably the issue is related to a not ready yet DOM element, according to the fact this issue does not happens in Firefox.

**Comment by halatmit** [comment] 2015-07-06 10:56
@Momoumar 
@fmntf 
Francesco, thanks for finding that.missing tag.   Momoumar will be looking at this.

**Comment by Momoumar** [comment] 2015-07-06 19:19
@fmntf Thank you for noticing this.
@halatmit, 
Regarding Francesco's note, a solution might be, seeing that the size for icon Image is fixed (16x16), we could just pass those values to ``` MockComponent::ClippedImagePrototype(String url, int left, int top, int width,
      int height) ```  instead of calling ```iconImage.getHeight()``` and ```iconImage.getHeight()```

**Comment by fmntf** [comment] 2015-07-07 10:09
Yes, that could be a solution.
If you put a breakpoint on `$buildTree` you can see that `this$static.iconImage.element` is something like  `<img src="data:image/png;base64,iVBORw....." width="16" height="16" class="gwt-Image">`

The image is rendered 16x16 via attributes which are then converted to style. If it is easy, instead of defining new size constants (ICON_IMAGE_WIDTH, ICON_IMAGE_HEIGHT) an improvement could be to reuse the same constants used in `width="16"`.

**Comment by Momoumar** [comment] 2015-07-07 22:50
@fmntf Where is the ```width="16"``` constant ? 
Do you mean  replacing ```ClippedImagePrototype(iconImage.getUrl(), iconImage.getOriginLeft(),iconImage.getOriginTop(), ICON_IMAGE_WIDTH, ICON_IMAGE_HEIGTH)``` with  ```ClippedImagePrototype(iconImage.getUrl(), iconImage.getOriginLeft(),iconImage.getOriginTop(), ICON_IMAGE_WIDTH, ICON_IMAGE_WIDTH)```

**Comment by fmntf** [comment] 2015-07-08 09:28
No, I meant that the `<img>` elements when it is created already has `width="16" height="16"`.
By the way, I cannot find where the 16 comes from.

I think your commit 8397ee54f915736693e0ee6eb7ff8389f8cc6e37 is fine to be merged (with separate width/height constants).

**Comment by Momoumar** [comment] 2015-07-09 01:25
@fmntf  The 16 comes from here: https://docs.google.com/document/d/1xk9dMfczvjbbwD-wMsr-ffqkTlE3ga0ocCE1KOb2wvw/pub

4. Implementation
    4a. Creating an Icon

**Comment by fmntf** [comment] 2015-07-09 08:06
Ok, but that's a specification document. I mean, when the <img> element is created, before to set width/height (with `ClippedImagePrototype`), the image has already a size of 16x16 px (I don't think Chrome adds width/height attributes according to the real image size). Who creates the `<img>` with `width="16" height="16"` ? I coudn't find that.

If we could find where that 16 cames from, we could use that constant instead of defining a new constant.

**Comment by jisqyv** [comment] 2015-07-12 23:52
Fixed in #454 Which is merged into the ucr branch

**Closed by jisqyv** 2015-07-12 23:52 UTC
