### ISSUE TITLE
Version numbering of Extensions

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#921] opened 2017-09-05 11:44 UTC
Topic from: https://community.thunkable.com/t/version-numbering-of-extensions/7321
> Some of the popular and actively developed extensions seem to evolve every few weeks. It becomes challenging to keep track of the versions based purely on their date of download and file size. Is there some version numbering available for Extensions, that I might not be aware of ?

A know that there is a VERSION field of the components in java code, but it is not visible for user on the website.
At least i forget to upgrade my extensions' VERSION field all the time...

so i advice to make the version number clearly displayed.
it may at least help reminding developers.

Thanks!

**Comment by ewpatton** [comment] 2017-09-05 13:02
This is a duplicate of #894.

**Closed by ewpatton** 2017-09-05 13:02 UTC
