### ISSUE TITLE
How about more color choices in the Designer

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#300] opened 2015-03-04 16:26 UTC
When you look at the list of choices available for colors in the blocks editor you get a much nicer UI widget with a wide variety of colors. By comparison, the version available in the Designer (presumably part of GWT) has a much more limited selection of colors.

**Comment by EnisM** [comment] 2015-03-07 01:31
+++

Never understood this... But at the same time, in that color list in the designer is almost impossible to reach all items on the drop down color list unless you've zoom WAYYYY out... Would be nice if the same selection box that pops up in blocks could pop up in the designer too...

**Comment by E-Hon** [comment] 2015-04-08 11:51
Is it possible to use the color input element instead?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color

OSX Safari, IOS Safari, IOS Chrome don't support it though. Android Firefox supports it but the choices are limited.

OSX, WIndows and Ubuntu all have a color picker

**Comment by E-Hon** [comment] 2016-02-21 12:51
i've done a little experiment with color input element.

It is as simple as < input type="text" > but its value must start with #. So we can't change # into &H in the __property editor__. We can only change it in __property__. The problem is when a project is being saved, only those values from __property editors__, but not from __property__, are copied into .scm file, resulting in buggy loading of the project if # stays in the __property editor__

we can change the saving mechanism to save values from __property__ instead but this will create a bigger issue than what this one is for. I don't think we want that. 

we can get rid of &H entirely and use # instead. but i think there are reasons for using &H but i haven't figured it out.

**Comment by ewpatton** [comment] 2017-10-28 18:57
This was implemented in ecb6659. It is available on ai2-test and will be in the next components release.

**Closed by ewpatton** 2017-10-28 18:57 UTC
