### ISSUE TITLE
.aar Library Support For Extension

### ISSUE THREAD

**Issue by aryanrauniking** [mit-cml/appinventor-sources#2218] opened 2020-06-29 07:46 UTC
From Many Days AppInventor Team Is Able To Add Support Of Many Features  ....Which Was Supposed To Impossible To For External component :/
But adding .aar support For Extension Will Be More Awesome :) If AppInventor Team Will Help To Add This Feature than It Would Be Great :)

**Comment by pavi2410** [comment] 2020-07-20 08:40
Duplicate of https://github.com/mit-cml/appinventor-sources/issues/2196

**Closed by pavi2410** 2020-07-20 08:40 UTC
Labels: feature request, status: new
