### ISSUE TITLE
Companion fails to "connect" to a YA app with error!

### ISSUE THREAD

**Issue by thequixotic** [mit-cml/appinventor-sources#507] opened 2015-08-15 17:02 UTC
Connecting Companion to a Project with errors in it will cause a crippled connection.
The problem is only there during connecting. The companion will be connected (technically) to the AI client.
But the companion will fail to load anything.

For example try connecting to a project that has blocks as shown below
![start_companion_error](https://cloud.githubusercontent.com/assets/4526473/9289872/047af4e4-439b-11e5-8a82-07c750a9b887.png)

It will fail to load the Companion. Even after you try to correct the error above, it still won't show any updates.You have to try reconnecting the Companion after correcting the error.
However once connected, you can have errors later(it just wont show an app with error ). You can see changes immediately after correcting all error.

No, I do NOT have an elegant solution to fix this issue. 
However I presume, that the ReplForm fails to get loaded by runtime.scm due to an entire fail to the first scheme.eval .. 

@halatmit, is this bug important to fix.

**Comment by halatmit** [comment] 2015-08-15 17:25
@jisqv PTAL

**Comment by jisqyv** [comment] 2015-08-15 17:51
Ack. I'll look at this tonight or tomorrow.

**Comment by jisqyv** [comment] 2015-08-16 02:13
@thequixotic @halatmit So I figured this one out. The problem is that during the initial load of the app there is a (begin expr ...) where each expr is one of the scheme expressions that sets up a component. An error in an early expr stop execution so later components do not get setup.

The work around is to fix the problem in the project and then make a change in the designer (any change). A change in the designer triggers an App reload which will reload all components. If there is not error this time, all will proceed normally.

I am working on a fix, which involves modifying (do-after-form-creation ...) in runtime.scm. The idea being to wrap a try-catch around each expr being evaluated and continue after an error *and* signal the error back to the blocks editor. It may or may not be possible to indicate the component with the error (still looking at that) but at least the user will be alerted to the problem.

I'll hack on this either tomorrow or next week, depending on what else is demanding my attention :-)

**Comment by jisqyv** [comment] 2015-08-16 02:14
@thequixotic @halatmit P.S. I may want to defer the final fix until after we merge the changes for "watch" which also hacks a lot of the code in that neighborhood.

**Comment by jisqyv** [comment] 2016-01-10 01:00
This was fixed with #604

**Closed by jisqyv** 2016-01-10 01:00 UTC
Labels: bug, issue: accepted
