### ISSUE TITLE
Accessing Textbox properties in another component's event causes compiled program to fail (Thread issue?)

### ISSUE THREAD

**Issue by myrtleTree33** [mit-cml/appinventor-sources#320] opened 2015-03-17 07:17 UTC
Hello everyone,

I am creating a new component, and my test app uses TextBox component as a debugger.

When the event is dispatched, the text view's background and text are changed.

However, this results in the following thread error:

![screenshot_2015-03-17-15-06-49](https://cloud.githubusercontent.com/assets/1506937/6682785/415a0210-ccb8-11e4-91cd-3ce754169116.png)

I can verify that the component's events are working.  Is there a bug with TextBox component?  Program as attached:

![selection_176](https://cloud.githubusercontent.com/assets/1506937/6682801/866d614e-ccb8-11e4-893b-b86be40356dc.png)

![selection_177](https://cloud.githubusercontent.com/assets/1506937/6682804/8a659064-ccb8-11e4-9b60-9a924bab6cfb.png)

**Comment by josmas** [comment] 2015-03-17 17:54
Hi @myrtleTree33 how are you dispatching the events from your own event code? This seems to happen only in your new created component, so most likely the problem is in that code. If you point us to a branch we can have a peek.

**Comment by josmas** [comment] 2015-05-24 18:29
closing this for now; feel free to re-open if needed.

**Closed by josmas** 2015-05-24 18:29 UTC
