### ISSUE TITLE
Multi-select status issue in design view

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#2055] opened 2020-02-23 04:41 UTC
**Describe the bug**

When user switch out of the web page with control pressed, the select mode of components would always multi-select mode unless use press and release control key again.

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Would detect the status of control key more "smartly"

**Steps to reproduce**

1. Open Design view, select any component
2. Press control key (left or right control keys behave the same)
3. Switch to any other tabs or windows
4. Release control key and switch back to App Inventor page
5. Try click on any other components in the component list or the viewer, you will see it's in multi-select mode even you are not pressing control key.

**Comment by ewpatton** [comment] 2020-02-24 14:42
Duplicate of #1987

**Closed** 2020-02-24 14:42 UTC
Labels: bug, duplicate, status: new
