### ISSUE TITLE
Investigate the 5MB limit

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#493] opened 2015-08-05 22:04 UTC
See if it makes sense to increase the 5MB limit on projects.
And/or create documentation on workarounds, like delayed uploading of assets.
See Taifun's advice  here:
https://puravidaapps.com/filebyfile.php

**Comment by josmas** [comment] 2016-02-14 21:10
closing this one as a duplicate of #700

**Closed by josmas** 2016-02-14 21:10 UTC
