### ISSUE TITLE
Wrong block type generated for "false" in typeblocking?

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#559] opened 2015-09-20 19:26 UTC
From Ralph:

If you pull a 'false' block out of the drawer you get a block whose type is logic_false
If you type 'false' in the background, you get a block whose type is logic_boolean

If you pull 'true' out of drawer, you get a block whose type is logic_boolean
If you type 'true', you get a block whose type is logic_boolean

If you pull 'false' out of the drawer and change it to 'true', its type is still logic_false.

**Comment by halatmit** [comment] 2015-09-20 19:31
PS from Ralph:
Actually, it looks to me like the blocktyping cases are correct -- i.e  assuming the correct type should be "logic_boolean".   I assume the blocktyping code covers when you type on the workspace background.  Everything is fine in those cases. 

The only anomalous case is when you pull the false block out of the drawer.  In that case its type is "logic_false".

**Comment by josmas** [comment] 2015-09-20 20:46
This seems to be by design in the drawers (typeblocks behaves correctly).
If you have a look at the types for 'and' and 'or', they behave in the exact same way (types
are logic_boolean and logic_or). They seemed to be used on blocks that use dropdowns, to have two (or more) blocks appear in the flyout, and the generator function just calls the 'generic' one as in https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/src/generators/yail/logic.js#L22

It isn't pretty, especially because the types do not change when you use the dropdown, so you end up with a 'true' block of type 'logic_false', or an 'and' block of the type 'logic_or', but they are
properly handled in the YAIL translation.

It might be possible to change the design, but I don't think this is a high priority (and would affect many other blocks... pretty much anything that uses a dropdown!).

I would close this issue, at least for now @halatmit

**Comment by halatmit** [comment] 2015-09-20 22:06
@josmas @ram8647 @jis @afmckinney 
From Paul:
These blocks were added before Blockly had the ability to customize the toolbox (ie the drawers) like you can today. Back then, blocks appeared in the order that they were in the file, so to get a "true" and "false" block, we needed two different block definitions. The blocks shared the same yail definitions since they generated the exact same code.

The long term fix is 1) have a better way of specifying the blocks in the toolbox (it should be independent from the order of the blocks in the block definition files), and 2) use the project upgrader to remove blocks that have different block types, but are the same block with a different default value for a field (and/or, true/false, all of the color blocks, etc).

**Comment by halatmit** [comment] 2015-09-22 12:47
Given the comments here, we'll hold it for future work.

**Comment by ewpatton** [comment] 2019-02-05 17:23
I think that the important thing here is that the semantics of the language are correct. The block types could easily be SHA256 hashes of the names and it wouldn't change anything so long as the YAIL that is generated is correct. We can't ever remove the existing definitions anyway because it would break loading older projects. If there's a strong objection, we can reopen this, but I think we should leave this as is.

**Closed by ewpatton** 2019-02-05 17:23 UTC
Labels: issue: noted for future Work
