### ISSUE TITLE
appinventor-sources cannot compile

### ISSUE THREAD

**Issue by jarwin123** [mit-cml/appinventor-sources#1707] opened 2019-05-19 09:06 UTC
![图片](https://user-images.githubusercontent.com/8475971/57979973-12f06a80-7a57-11e9-8540-dddb77e9f659.png)

my os：
   centos 7
java： 
         
![图片](https://user-images.githubusercontent.com/8475971/57980046-57c8d100-7a58-11e9-94cc-8ac96838ee79.png)

app engine:
     
![图片](https://user-images.githubusercontent.com/8475971/57980049-69aa7400-7a58-11e9-9590-793111552c0b.png)
ant :
   
![图片](https://user-images.githubusercontent.com/8475971/57980051-76c76300-7a58-11e9-8630-c6138c9cdc17.png)

**Comment by jarwin123** [comment] 2019-05-19 09:21
this is compie log:
[a.txt](https://github.com/mit-cml/appinventor-sources/files/3194930/a.txt)

**Comment by ankritisachan** [comment] 2019-05-19 09:29
Hi, this is not a bug actually.
To build successfully, you need to install 32-bit compatible libraries on your system (particularly zlib, libc, and libstdc++).
This has been discussed in our forum.
Solution for the same error is mentioned here - [Build Failed](https://groups.google.com/forum/#!msg/app-inventor-open-source-dev/9E3ql99V97Q/9vE1J-K9AQAJ).
You can also check here - [Additional Dependencies for 64-bit Linux Systems](https://groups.google.com/forum/#!msg/app-inventor-open-source-dev/9LjJ6cVAlJQ/YGNcPdOkx7YJ)
We will be updating the README soon.

**Comment by jarwin123** [comment] 2019-05-19 10:07
![图片](https://user-images.githubusercontent.com/8475971/57980625-67e4ae80-7a60-11e9-8ccd-f9677801e42a.png)
![图片](https://user-images.githubusercontent.com/8475971/57980630-7337da00-7a60-11e9-928f-bb90456a6854.png)

thank you,
i compie success,but when i run server , but the browser is empty,
 

my brower is chrome

**Comment by jarwin123** [comment] 2019-05-19 10:09
![图片](https://user-images.githubusercontent.com/8475971/57980707-34eeea80-7a61-11e9-9c56-a6fd0617f2f4.png)

**Comment by jarwin123** [comment] 2019-05-19 10:16
what wrong with my operator?  the web browser is empty.

**Comment by ankritisachan** [comment] 2019-05-19 10:25
I am not sure about this. It should automatically direct you to the login page.
Maybe try: http://54.39.133.166:8888/login/

**Comment by jarwin123** [comment] 2019-05-19 11:19
try  input http://54.39.133.166:8888/login/  in my browser 
i set my user,
![图片](https://user-images.githubusercontent.com/8475971/57981500-dfb7d680-7a6a-11e9-83c1-515ec022cf1f.png)

but my email no message from appinventor,

this version of appinventor cannot use normal?

**Comment by jarwin123** [comment] 2019-05-19 11:25
ant:
![图片](https://user-images.githubusercontent.com/8475971/57981589-c95e4a80-7a6b-11e9-9f56-5495fe8cedc0.png)
ant tests:
![图片](https://user-images.githubusercontent.com/8475971/57981586-b9466b00-7a6b-11e9-9dbe-bde34e8cfd82.png)

**Comment by ankritisachan** [comment] 2019-05-19 11:43
After 'ant', run the main server using instructions [here](https://github.com/ankritisachan/appinventor-sources#running-the-servers).
Since you are running AppInventor on localhost, just use links without any change(you don't need to set password, etc.). 
Use:
" Click Here to use your Google Account to login -> Log In " and you will be in.

**Comment by jarwin123** [comment] 2019-05-19 11:48
i also try your method, i cannot login ,

how to setup configure ?

**Comment by jarwin123** [comment] 2019-05-19 12:01
![图片](https://user-images.githubusercontent.com/8475971/57981932-c31e9d00-7a70-11e9-9e33-7537b34ef5b1.png)
![图片](https://user-images.githubusercontent.com/8475971/57981936-d7fb3080-7a70-11e9-93f0-72b0cf999a5d.png)

**Comment by jarwin123** [comment] 2019-05-19 12:02
![图片](https://user-images.githubusercontent.com/8475971/57981955-05e07500-7a71-11e9-9a0a-28e7deee5d51.png)

**Comment by ColinTree** [comment] 2019-06-12 09:27
Try Google Chrome please

**Closed** 2019-09-14 15:55 UTC
