### ISSUE TITLE
ChartData2D Component Needs Property to Define Range of Y Axis

### ISSUE THREAD

**Issue by bobparks** [mit-cml/appinventor-sources#2787] opened 2022-12-16 22:32 UTC
**Describe the bug**
ChartData2D generates the range of the Y axis from the data, but this can be problematic when visualizing two comparable datasets that differ in the range of Y. It creates a false comparison, as shown below.

For example, if you looked at the annual ice duration data of these two lakes, top and bottom, they would seem similar. The range of the top lake, however, starts around 70 instead of 0. 

![Screenshot_20221216-170808](https://user-images.githubusercontent.com/39967592/208198276-2a3bb86c-fb6a-4a17-b571-9db140ee6ae3.jpg)
By changing the Y range to 0 for both (artificially adding a leading 0 to the data), the top graph shows a truer picture — that the top lake has less variation year-to-year than the bottom lake (it is more shallow and therefore a bit more resilient to climate change). 
![Screenshot_20221216-170718](https://user-images.githubusercontent.com/39967592/208198666-525949e6-be09-43f1-9047-5967932647eb.jpg)

For kids to compare two datasets accurately, would be great to have a parameter in the ChartData2D properties panel to define this range.

@stezelMIT, @anqizzz8989 

**Affects**

- [ x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

**Steps to reproduce**

**Comment by dhruvpatidar359** [comment] 2023-01-19 16:39
This issue seems interesting to me , can anyone please guide me how i can track this issue in the code base , what steps i should follow ? -- i am beginner with this  project , that's why i am asking .

**Comment by stezelMIT** [comment] 2023-01-19 18:21
I believe @ewpatton already fixed that, correct Evan?

**Comment by dhruvpatidar359** [comment] 2023-01-19 18:31
ok , if ewpatton has not corrected it then , i think that it can be corrected by doing some changes in the file Char2DDataModel.java

**Comment by dhruvpatidar359** [comment] 2023-01-19 18:31
ok , if ewpatton has not corrected it then , i think that it can be corrected by doing some changes in the file Char2DDataModel.java

**Comment by dhruvpatidar359** [comment] 2023-01-20 11:33
Hello @ewpatton  sir ,is the issue resolved or i can work on this ?

**Comment by dhruvpatidar359** [comment] 2023-01-20 17:15
I checked it , the problem is still there in the current version , here  you can see

**Comment by dhruvpatidar359** [comment] 2023-01-20 17:15
![WhatsApp Image 2023-01-20 at 10 44 47 PM (1)](https://user-images.githubusercontent.com/103873587/213762270-f7e5af39-ae79-45b8-a269-4b3fb8708394.jpeg)
![WhatsApp Image 2023-01-20 at 10 44 47 PM](https://user-images.githubusercontent.com/103873587/213762278-79eb563f-aead-40bd-990f-99489777881b.jpeg)

**Comment by stezelMIT** [comment] 2023-01-20 17:23
I think the issue has been addressed and is now on the test servers, but not merged yet.  Correct @ewpatton @bobparks ?

**Comment by ewpatton** [comment] 2023-01-20 20:38
That's correct. The branch in question needs to be cleaned up a bit because I implemented some other changes to spreadsheets that in hindsight didn't work so I backed them out. From the end user's POV it won't make any different but in terms of keeping the code base clean it's better for me to do the work to fix up the branch before publishing the PR.

**Comment by ewpatton** [comment] 2024-12-31 05:55
This was fixed by #2812

**Closed by ewpatton** 2024-12-31 05:55 UTC
Labels: bug, status: new
