### ISSUE TITLE
copy & paste components, maintaining properties

### ISSUE THREAD

**Issue by JoshESheldon** [mit-cml/appinventor-sources#840] opened 2016-08-30 15:05 UTC
Rather than having to drag out multiple instances of a component, particularly user interface components, it would be great to be able to copy an existing component & paste it, and have it maintain state of properties.

**Comment by ewpatton** [comment] 2016-09-19 02:01
Possible duplicate of #726?

**Comment by jsheldonmit** [comment] 2016-11-10 07:38
Yes, it appears to be.

I’m not sue the other notes that the properties should be maintained, but perhaps that’s obvious

================
Josh Sheldon
Director of Programs – MIT App Inventor
MIT Center for Mobile Learning
32 Vassar St., Room 32-G528
http://whereis.mit.edu/?go=32
Cambridge, MA 02139
mobile phone: 617-671-5491

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>

**Closed** 2020-06-12 02:05 UTC
