### ISSUE TITLE
Text deobfuscate does not support Unicode

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#2095] opened 2020-03-11 11:47 UTC
![image](https://user-images.githubusercontent.com/3827464/76413794-0ca9f100-63d1-11ea-8c0f-9b9a43dab688.png)
![image](https://user-images.githubusercontent.com/3827464/76413832-1fbcc100-63d1-11ea-90d8-cf7c9cbe8992.png)

**Comment by ewpatton** [comment] 2020-03-11 14:18
Possible dupe of #1529

**Comment by wxbit** [comment] 2020-03-12 02:50
it's the same…

**Closed** 2020-03-18 10:19 UTC
Labels: bug, status: new
