### ISSUE TITLE
implement manifest-merger

### ISSUE THREAD

**Issue by AKBIROCK3** [mit-cml/appinventor-sources#2245] opened 2020-07-17 00:28 UTC
First sorry cause this is my second time asking this
i wish you add support for manifest-merger 
i've started learning how to create extensions recently and i've create some extensions
when i was trying to learn the most thing i hated is write activities lines and meta-data line from the aar
and sometimes i write it wrong while sometimes i need to decompile my app to check if it was correct or not you know how hard it is to write all this small stuff and sometimes i even leave the extension im creating just because of it
so i told myself that it's okay to ask again hopefully something will change since this feature will help many developers who wants to learn or contribute to appinventor

some links:
https://developer.android.com/studio/build/manifest-merge.html
https://maven.google.com/web/index.html?#com.android.tools.build:manifest-merger

**Comment by pavi2410** [comment] 2020-07-20 08:43
Duplicate of https://github.com/mit-cml/appinventor-sources/issues/2196.

I did my research on integrating manifest merger earlier and I will be working on that soon.

**Closed** 2020-07-20 08:43 UTC
Labels: feature request, status: new
