### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by aminelabs** [mit-cml/appinventor-sources#869] opened 2017-02-07 14:09 UTC
ComponentList:
    [javac] Compiling 194 source files to C:\Users\Mohamed Ibrahim\appinventor-sources-master\appinventor\components\build\classes\ComponentList
    [javac] javac: invalid flag: Ibrahim\appinventor-sources-master\appinventor\components\build/AnnotationProcessors.jar
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
C:\Users\Mohamed Ibrahim\appinventor-sources-master\appinventor\build-common.xml:399: The following error occurred while executing this line:
C:\Users\Mohamed Ibrahim\appinventor-sources-master\appinventor\components\build.xml:378: The following error occurred while executing this line:
C:\Users\Mohamed Ibrahim\appinventor-sources-master\appinventor\components\build.xml:230: Compile failed; see the compiler error output for details.

Total time: 25 seconds

C:\Users\Mohamed Ibrahim\appinventor-sources-master\appinventor\buildserver>

**Comment by josmas** [comment] 2017-02-07 14:25
Hi there, please ask for help in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev) instead of opening an issue. The problem is with your local setup. Closing this now.

**Closed by josmas** 2017-02-07 14:25 UTC
