### ISSUE TITLE
Firebase AppendValue; Previous Value was Empty Error

### ISSUE THREAD

**Issue by GOTFire** [mit-cml/appinventor-sources#1150] opened 2018-01-31 14:33 UTC
Hello

I know firebase still experimental for usage.I found a bug 

When screen1 opened and i dont wait 1-2 sec and click button its bugged.But if i am wait ı dont see any AppendValue error

When ı open my app and click button.My app try appendValue to Tag (Tag is not empty,its a list(empty list or filled with user names))

Button Clicked İmage 
https://lh3.googleusercontent.com/-1KvsVMebFKk/WnHRORirTkI/AAAAAAAAK5U/9gvQu9kRGgsSJveqbkZkPsYQWIv9ifT0wCLcBGAs/s1600/Ekran%2BAl%25C4%25B1nt%25C4%25B1s%25C4%25B1.PNG

Here video
https://streamable.com/otflo

**Comment by harisriaz17** [comment] 2018-02-07 06:40
I am going to try to fix this issue.

**Comment by GOTFire** [comment] 2018-02-07 14:27
Thanks waiting for fix

**Comment by josmas** [comment] 2018-03-28 15:47
@GOTFire are you sure that the tag is not empty when you open the app? Do you have a timer that adds that adds that first list to the tag?

I cannot reproduce this if I first use `StoreValue` once, even if I restart the app and click append immediately. Sharing the initialisation that you use for your app may be useful here.

**Comment by GOTFire** [comment] 2018-03-28 18:18
I just make a little project for you.Here 
![d646b5c0-34aa-45a2-9b67-0748806e9e7e](https://user-images.githubusercontent.com/23584565/38048043-f6a4e77a-32cc-11e8-9421-e5e719c799ea.png)

I added AppendValue block to Screenİnit so we dont need click button.If your firebase settings(URL,token) resetted you will see error messeage at the first time.Change it with your own and hit the button now close app.And open app you will see error messeage just like me.I can send video if you want



https://drive.google.com/file/d/1ZWBeW6n2gFsoLx85vYKRQK-vNZV3xuop/view?usp=sharing

**Comment by josmas** [comment] 2018-03-28 19:42
@GOTFire so the thing is that what you are doing in the initialise block is asynchronous, so it might not finish before you click on the button, which basically means that the tag was not yet set, and the error makes sense.

I wouldn't use Initialize in this scenario. But if you want to use it, you can catch the error and let the user know they have to wait. Or disable the button until you don't get any errors from Firebase. It is not ideal, but I can't think of other ways to do it right now.

**Comment by GOTFire** [comment] 2018-03-28 20:20
@josmas 
I already find solution for this problem.Just added Append Block to Firebase Error block.
İf Error=Previues ... 
Append Value

Its fix my problem

**Comment by josmas** [comment] 2018-03-28 21:57
sounds good. I'll close this issue then. Thanks!

**Closed by josmas** 2018-03-28 21:57 UTC

**Comment by MartinHerraizH** [comment] 2021-01-16 15:33
I had a similar problem: "Previous value was empty" error when trying to append to in FireBase.
I discovered that the problem only happens when the firs item of the list of the existing content in FireBase (to which I tried to append) contained an space " ". Like when puting your name and surname together in a single text box.
I also observed that, when trying to retreive information from the data base, if it was a sentence or string that contained spaces, only the first word was retrieved, and the rest was missing.
Does someone have a solution (other than to edit the sentence before writing to the database, forcing to replace the spaces by some other thing?
