### ISSUE TITLE
How to use the whitelist

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1158] opened 2018-02-14 17:23 UTC
Is there any document explaining how to use the users whitelist?

**Comment by ewpatton** [comment] 2018-02-19 23:42
@barreeeiroo As far as I am aware, the Whitelist feature isn't actually used anywhere. The original whitelist implementation was written at Google, but it is not employed anywhere in the source (it is referenced in commented out code in ObjectifyStorageIo). The WhitelistData object can be used to manage the whitelist, but there isn't a UI implement to manipulate the data in any way. However, once you've created a single WhitelistData object, you should be able to create new instances via the GAE console.

@jisqyv @afmckinney @halatmit Can any of you expand on this?

**Comment by barreeeiroo** [comment] 2018-02-20 00:28
I found whitelist.py on the misc folder, but all errors are making me mad (SSL problems, Libraries problems... I tried in both Windows and Linux, and in none of them worked without problems)
I already supposed that once I create the first object to WhitelistData it will be visible on Datastore Admin page and consequently to directly create new entries, but I wasn't able to introduce the first one
I've also tried to access manually to the remote_api trying to make a manual push, but it was impossible though

**Comment by jisqyv** [comment] 2018-02-20 02:51
There are two ways forward from here.

To use the whitelist you need to set use.whitelist to true in appengine-web.xml.

The Whitelist.java module is obsolete. It reads a whitelist from a file in war/WEB-INF/whitelist. However if you look at the line 196 in OdeAuthFilter.java you can see where the code that calls the Whitelist module is commented out and replaced with the version that reads from the data store. You can switch which line is commented out and it will again use the Whitelist.java module. However you must do a deployment to update the whitelist file in WEB-INF.

The other thing you can do is create the WhiteList kind the data store. You can use the /remote_api (I use it all the time from Python). However you will need to patch web.xml first (which is probably why you are being frustrated). For some reason our version is patched in our "branding" changes, but not on master. I'll submit a pull request this week to fix it in master. In the meantime you can find the patch you need here:

  http://ipfs.io/ipfs/QmSu8ooHPJgbMKWcpvPZyAcDFzk2uxuCoAKP1cEPPBNGwq/patch.txt

-Jeff

**Comment by barreeeiroo** [comment] 2018-02-20 15:51
Yeah, what I've used was the static whitelist, but as you said it's very annoying having to deploy a new version always
![screenshot_2018-02-20-16-48-41-238_com fastaccess github](https://user-images.githubusercontent.com/19251112/36433950-19cec954-165e-11e8-9915-e849f07fd53f.png)

The error I get using the script (after fixing lots of them before) is this:
```
ERROR:root:ssl.wrap_socket faled with [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
current python version is:
 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
try upgrading your python.

Traceback (most recent call last):
  File "D:\Makeroid\appinventor\misc\whitelist\whitelist.py", line 208, in <module>
    main()
  File "D:\Makeroid\appinventor\misc\whitelist\whitelist.py", line 63, in main
    rpc_server_factory=appengine_rpc.HttpRpcServer)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 1124, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 829, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 422, in Send
    self._Authenticate()
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 555, in _Authenticate
    super(HttpRpcServer, self)._Authenticate()
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 293, in _Authenticate
    auth_token = self._GetAuthToken(credentials[0], credentials[1])
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 232, in _GetAuthToken
    response = self.opener.open(req)
  File "C:\Python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\google_appengine\/lib/fancy_urllib\fancy_urllib\__init__.py", line 415, in do_open
    raise url_error
URLError: <urlopen error [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed>
```
It appears after inputting the email and the password, either correct or wrong

**Comment by barreeeiroo** [comment] 2018-02-20 15:55
And your fix seems that removes that only admins can access it
But the account I've tried was admin on the server (I check on Datastore and also the Admin dropdown appeard) so I guess that fix isn't the solution to that error
I deduced that there's a problem with SSL on the script, but I don't know why

**Comment by jisqyv** [comment] 2018-02-20 18:10
> And your fix seems that removes that only admins can access it

The /remote_api target goes directly to Google provided code. The Google code now checks that you are the admin, so our check became both redundant and breaking. So you had to do it the way we did some number of years ago, but now you *must* do it without requiring admin, or it breaks.

I'll poke at the whitelist.py script and see if I can get it to work.

**Comment by barreeeiroo** [comment] 2018-02-20 18:52
So, if I remove that admin check, then that SSL error will disappear?

**Comment by jisqyv** [comment] 2018-02-20 18:53
I'm not sure, but if you don't make the change it certainly won't work.

**Comment by barreeeiroo** [comment] 2018-02-20 23:45
@jisqyv I've tried right now:
```
D:\Makeroid\appinventor\misc\whitelist>C:\Python27\python.exe whitelist.py -h xn--nxa.builder.makeroid.io
Module readline not available.
Using whitelist for input
Connecting to something.makeroid.io
Email: diego@makeroid.io
Password:
ERROR:root:ssl.wrap_socket faled with [Errno 8] _ssl.c:499: EOF occurred in violation of protocol
current python version is:
 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
try upgrading your python.
Traceback (most recent call last):
  File "whitelist.py", line 208, in <module>
    main()
  File "whitelist.py", line 63, in main
    rpc_server_factory=appengine_rpc.HttpRpcServer)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 1124, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 829, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 422, in Send
    self._Authenticate()
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 555, in _Authenticate
    super(HttpRpcServer, self)._Authenticate()
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 293, in _Authenticate
    auth_token = self._GetAuthToken(credentials[0], credentials[1])
  File "D:\google_appengine\google\appengine\tools\appengine_rpc.py", line 232, in _GetAuthToken
    response = self.opener.open(req)
  File "C:\Python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\google_appengine\/lib/fancy_urllib\fancy_urllib\__init__.py", line 415, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:499: EOF occurred in violation of protocol>

D:\Makeroid\appinventor\misc\whitelist>
```
Even changing line 58 to `secure = False` doesn't work

**Comment by jisqyv** [comment] 2018-02-21 00:39
@barreeeiroo Is something.makeroid.io an App Engine instance or an instance of the dev server?

**Comment by barreeeiroo** [comment] 2018-02-21 12:36
It's an AppEngine instance (not local)
And I've also tried local but gives 500 Internal Server Error (I'll post
here logs in a few hours)

**Comment by jisqyv** [comment] 2018-02-21 18:18
@barreeeiroo I have updated the whitelist.py script to use OAUTH2, which is how you need to authenticate to appengine using more modern versions of the appengine SDK. This version works for me. Let me know if it works for you and if not, how it fails.

Here it is:  https://github.com/jisqyv/appinventor-sources/blob/fixwhitelist/appinventor/misc/whitelist/whitelist.py

**Comment by barreeeiroo** [comment] 2018-02-21 18:29
If I use Python IDLE it gives `NameError: global name 'Path' is not defined`
If I use CMD it gives `ImportError: Use of OAuth credentials requires the oauth2client module: No module named oauth2client`

**Comment by jisqyv** [comment] 2018-02-21 18:40
@barreeeiroo Ooops. I didn't check it against localhost (and it may not work there for other reasons). I have fixed the script anyway. But you should try it against a real app engine instance.

**Comment by barreeeiroo** [comment] 2018-02-21 18:43
It gives this error now:
```
D:\Makeroid\appinventor\misc\whitelist>C:\Python27\python.exe whitelist.py -h something.makeroid.io
Module readline not available.
Using whitelist for input
Connecting to something.makeroid.io
Traceback (most recent call last):
  File "whitelist.py", line 218, in <module>
    main()
  File "whitelist.py", line 64, in main
    secure=secure)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 1039, in ConfigureRemoteApiForOAut
h
    rpc_server_factory=rpc_server_factory)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 1124, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "D:\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 829, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "D:\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Python27\lib\site-packages\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "C:\Python27\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey
)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1319, in _conn_request
    conn.connect()
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1092, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate ve
rify failed

D:\Makeroid\appinventor\misc\whitelist>
```

BTW, thanks for your help @jisqyv 👍

**Comment by jisqyv** [comment] 2018-02-21 18:47
@barreeeiroo The error you are getting is SSL is failing to verify the certificate that Google is presenting to you.

I checked the certificate path with openssl:
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.appspot-preview.com
   i:/C=US/O=Google Trust Services/CN=Google Internet Authority G3
 1 s:/C=US/O=Google Trust Services/CN=Google Internet Authority G3
   i:/OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign

You should check to see if you have the GobalSign Root CA - R2 in your certificate root store.

**Comment by barreeeiroo** [comment] 2018-02-21 18:53
I'm checking now on a Debian VM with an instance hosted on AppEngine

BTW, is this error normal? `NameError: global name 'rpc_server_factory' is not defined`

**Comment by jisqyv** [comment] 2018-02-21 18:59
@barreeeiroo Yet another bug (leftover from where I copied the code). Again, I'm not sure that even with fixes it will work for the devserver. That is because the appengine SDK deprecated using passwords, but you cannot use oauth2 for the dev server. When I need to talk to the dev server, I have an older copy of the SDK where passwords still work.

Try to get it to work with an App Engine hosted instance.

**Comment by barreeeiroo** [comment] 2018-02-21 19:02
Okey, I executed `pip install google-api-client-python` and trying with an AppEngine hosted instance I get this error:
![image](https://user-images.githubusercontent.com/19251112/36499595-0e0ef9d8-1742-11e8-9665-ddcc8cfa984c.png)

**Comment by barreeeiroo** [comment] 2018-02-21 19:07
I fixed that error, but now I get this:
```
Traceback (most recent call last):
  File "whitelist.py", line 218, in <module>
    main()
  File "whitelist.py", line 64, in main
    secure=secure)
  File "/home/barreeeiroo/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 1039, in ConfigureRemoteApiForOAuth
    rpc_server_factory=rpc_server_factory)
  File "/home/barreeeiroo/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 1124, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/home/barreeeiroo/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 829, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "/home/barreeeiroo/google_appengine/google/appengine/tools/appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1319, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1069, in connect
    self.ssl_version, self.host)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 97, in _ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:581)
```

**Comment by barreeeiroo** [comment] 2018-02-21 19:27
I think the best way to solve this is to inject manually on the deployment a demo entry, no?
It seems like the script is very buggy

**Comment by jisqyv** [comment] 2018-02-21 19:31
@barreeeiroo Try:

pip install pyopenssl ndg-httpsclient pyasn1

**Comment by barreeeiroo** [comment] 2018-02-21 19:43
```
barreeeiroo@barreeeiroo ~/Downloads> sudo pip install pyopenssl ndg-httpsclient pyasn1
[sudo] password for barreeeiroo:
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in /usr/lib/pymodules/python2.7
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.2.1 in /usr/lib/python2.7/dist-packages (from pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): cffi>=0.8 in /usr/lib/python2.7/dist-packages (from cryptography>=0.2.1->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/dist-packages (from cffi>=0.8->cryptography>=0.2.1->pyopenssl)
Cleaning up...
```

But:

```
barreeeiroo@barreeeiroo ~/Downloads> sudo pip install --upgrade pyopenssl ndg-httpsclient
^CCleaning up...
Operation cancelled by user
Storing debug log for failure in /root/.pip/pip.log
barreeeiroo@barreeeiroo ~/Downloads> sudo pip install --upgrade pyopenssl ndg-httpsclient pyasn1
Downloading/unpacking pyopenssl from https://pypi.python.org/packages/79/db/7c0cfe4aa8341a5fab4638952520d8db6ab85ff84505e12c00ea311c3516/pyOpenSSL-17.5.0-py2.py3-none-any.whl#md5=487aa7248e7389c2abd05c212cf6872a
  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking ndg-httpsclient from https://pypi.python.org/packages/fb/ab/8a8a0715eb71607eb0aefdca68a688041ca1dd92f8e049b962092fa5e513/ndg_httpsclient-0.4.4-py2-none-any.whl#md5=7b0c630d6aa3cfc696e65286aad41953
  Downloading ndg_httpsclient-0.4.4-py2-none-any.whl
Downloading/unpacking pyasn1 from https://pypi.python.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl#md5=766a80e17caafe179f0b6d56569c63d4
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB): 71kB downloaded
Downloading/unpacking six>=1.5.2 from https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468 (from pyopenssl)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking cryptography>=2.1.4 (from pyopenssl)
  Downloading cryptography-2.1.4.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-W1iRzH/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-W1iRzH/cryptography
Storing debug log for failure in /root/.pip/pip.log
barreeeiroo@barreeeiroo ~/Downloads>
```

**Comment by jisqyv** [comment] 2018-02-21 19:45
@barreeeiroo Try just the pyopenssl

**Comment by barreeeiroo** [comment] 2018-02-21 19:46
```
barreeeiroo@barreeeiroo ~/Downloads> sudo pip install --upgrade pyopenssl
Downloading/unpacking pyopenssl from https://pypi.python.org/packages/79/db/7c0cfe4aa8341a5fab4638952520d8db6ab85ff84505e12c00ea311c3516/pyOpenSSL-17.5.0-py2.py3-none-any.whl#md5=487aa7248e7389c2abd05c212cf6872a
  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking six>=1.5.2 from https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468 (from pyopenssl)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking cryptography>=2.1.4 (from pyopenssl)
  Downloading cryptography-2.1.4.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-XWD5JU/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-XWD5JU/cryptography
Storing debug log for failure in /root/.pip/pip.log
barreeeiroo@barreeeiroo ~/Downloads>
```

Weird

**Comment by jisqyv** [comment] 2018-02-21 19:50
@barreeeiroo Hmmm. Is this an ubuntu or debian system?

**Comment by barreeeiroo** [comment] 2018-02-21 19:53
Debian 8 Jessie

**Comment by jisqyv** [comment] 2018-02-21 20:03
Well, the problem isn't the script at this point. It is something to do with your python installation's SSL software. I've been using Google to find information about other people having a similar problem (which is where the recommendation to pip install pyopenssl came from). But at this point I'm kinda stumped. Famous last words: "It works for m."

**Comment by barreeeiroo** [comment] 2018-02-21 20:08
😂 
I'm going to try to inject the entry manually making some sh*t of code somewhere, and place there a demo email

**Comment by jisqyv** [comment] 2018-02-21 20:10
@barreeeiroo Good Luck!

**Comment by barreeeiroo** [comment] 2018-02-21 20:15
Adding this seems to be work:
![image](https://user-images.githubusercontent.com/19251112/36503098-4f973f50-174c-11e8-9168-1104172dd7a8.png)
After the demo entry is created just remove that ugly code from there and it's done

I'll let you know when it's uploaded the new version

**Comment by jisqyv** [comment] 2018-02-21 20:17
@barreeeiroo Crud, but effective! :-)

**Comment by barreeeiroo** [comment] 2018-02-21 21:15
I found a workaround! @jisqyv
If you go to the Datastore Entities browser, you'll see lots of parameters on the URL. Then find one with key `kind` and replace thr value with WhiteListData (`&kind=WhiteListData`). Hit enter, and you'll see that Google sais that there are no entities, but you will that you are browsing the WhiteListData class. Consequently, hit Create Entity, and set ID AutoGenerated, and add a parameter `emailLower` with the value. And you can add as much as you want
And it's done, without any script or any ugly code!

**Comment by jisqyv** [comment] 2018-02-21 21:16
@barreeeiroo Great!

**Comment by barreeeiroo** [comment] 2018-02-21 21:17
I attach some screenshots:
![screenshot_2018-02-21-22-16-05-988_com android chrome](https://user-images.githubusercontent.com/19251112/36505791-e3254db8-1754-11e8-9be6-074e1cc274cc.png)
![screenshot_2018-02-21-22-15-30-094_com android chrome](https://user-images.githubusercontent.com/19251112/36505799-e8a36464-1754-11e8-9081-9616ebc53ddf.png)
I've done it with WhiteListData2 class, because WhiteListData was already created, but the procedure is the same

**Comment by jisqyv** [comment] 2018-02-22 16:37
I have submitted #1160 which updates whitelist.py as well as the permissions on /remote_api. It works for me both against the dev server and a deployed app on App Engine. We'll close this issue out when that PR is merged.

**Closed** 2018-08-15 20:40 UTC
Labels: question
